//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantaPiloto.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlantaPiloto.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráficos.
        /// </summary>
        public static string btnChart_txt {
            get {
                return ResourceManager.GetString("btnChart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string btnClose_txt {
            get {
                return ResourceManager.GetString("btnClose_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string btnFile_txt {
            get {
                return ResourceManager.GetString("btnFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string btnFinish_txt {
            get {
                return ResourceManager.GetString("btnFinish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string btnOpen_txt {
            get {
                return ResourceManager.GetString("btnOpen_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir.
        /// </summary>
        public static string btnReceive_txt {
            get {
                return ResourceManager.GetString("btnReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string btnSend_txt {
            get {
                return ResourceManager.GetString("btnSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string btnStart_txt {
            get {
                return ResourceManager.GetString("btnStart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string btnVar_txt {
            get {
                return ResourceManager.GetString("btnVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string ConfigForm_txt {
            get {
                return ResourceManager.GetString("ConfigForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles.
        /// </summary>
        public static string gBoxControls_txt {
            get {
                return ResourceManager.GetString("gBoxControls_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string gBoxProyect_txt {
            get {
                return ResourceManager.GetString("gBoxProyect_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string lblConfigProDesc_txt {
            get {
                return ResourceManager.GetString("lblConfigProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del proyecto.
        /// </summary>
        public static string lblConfigProName_txt {
            get {
                return ResourceManager.GetString("lblConfigProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lblConfigTitle_txt {
            get {
                return ResourceManager.GetString("lblConfigTitle_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puertos.
        /// </summary>
        public static string lblPorts_txt {
            get {
                return ResourceManager.GetString("lblPorts_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string lblProDesc_txt {
            get {
                return ResourceManager.GetString("lblProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto:.
        /// </summary>
        public static string lblProName_txt {
            get {
                return ResourceManager.GetString("lblProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir.
        /// </summary>
        public static string lblReceive_txt {
            get {
                return ResourceManager.GetString("lblReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string lblSend_txt {
            get {
                return ResourceManager.GetString("lblSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaz Planta Piloto.
        /// </summary>
        public static string MainForm_txt {
            get {
                return ResourceManager.GetString("MainForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de configuración |*.txt.
        /// </summary>
        public static string showDialogFilter {
            get {
                return ResourceManager.GetString("showDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione archivo de configuración.
        /// </summary>
        public static string showDialogTitle {
            get {
                return ResourceManager.GetString("showDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string toolStripMenuItemAbout_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemAbout_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicaciones.
        /// </summary>
        public static string toolStripMenuItemCommunication_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCommunication_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string toolStripMenuItemConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear configuración.
        /// </summary>
        public static string toolStripMenuItemCreateConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCreateConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string toolStripMenuItemEnglish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemEnglish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelpHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelpHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string toolStripMenuItemLanguage_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLanguage_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar configuración.
        /// </summary>
        public static string toolStripMenuItemLoadConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLoadConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar configuración.
        /// </summary>
        public static string toolStripMenuItemModifyConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemModifyConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string toolStripMenuItemOthers_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemOthers_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string toolStripMenuItemSerie_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSerie_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string toolStripMenuItemSpanish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSpanish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual de usuario.
        /// </summary>
        public static string toolStripMenuItemUserManual_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemUserManual_txt", resourceCulture);
            }
        }
    }
}
