//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantaPiloto.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlantaPiloto.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear gráficas.
        /// </summary>
        public static string btnAcceptChart_txt {
            get {
                return ResourceManager.GetString("btnAcceptChart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear archivo.
        /// </summary>
        public static string btnAcceptFile_txt {
            get {
                return ResourceManager.GetString("btnAcceptFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar variable.
        /// </summary>
        public static string btnAddVar_txt {
            get {
                return ResourceManager.GetString("btnAddVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancel_txt {
            get {
                return ResourceManager.GetString("btnCancel_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráficos.
        /// </summary>
        public static string btnChart_txt {
            get {
                return ResourceManager.GetString("btnChart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar.
        /// </summary>
        public static string btnChartAmount_txt {
            get {
                return ResourceManager.GetString("btnChartAmount_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string btnClose_txt {
            get {
                return ResourceManager.GetString("btnClose_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnExit_txt {
            get {
                return ResourceManager.GetString("btnExit_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string btnFile_txt {
            get {
                return ResourceManager.GetString("btnFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detener guardado.
        /// </summary>
        public static string btnFileStop_txt {
            get {
                return ResourceManager.GetString("btnFileStop_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string btnFinish_txt {
            get {
                return ResourceManager.GetString("btnFinish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar imagen.
        /// </summary>
        public static string btnLoadImage_txt {
            get {
                return ResourceManager.GetString("btnLoadImage_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string btnOpen_txt {
            get {
                return ResourceManager.GetString("btnOpen_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir.
        /// </summary>
        public static string btnReceive_txt {
            get {
                return ResourceManager.GetString("btnReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string btnRefreshPorts_txt {
            get {
                return ResourceManager.GetString("btnRefreshPorts_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string btnSaveConfig_txt {
            get {
                return ResourceManager.GetString("btnSaveConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string btnSend_txt {
            get {
                return ResourceManager.GetString("btnSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string btnStart_txt {
            get {
                return ResourceManager.GetString("btnStart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string btnVar_txt {
            get {
                return ResourceManager.GetString("btnVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráfico.
        /// </summary>
        public static string ChartForm_txt {
            get {
                return ResourceManager.GetString("ChartForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundos.
        /// </summary>
        public static string chartXAxisLabel {
            get {
                return ResourceManager.GetString("chartXAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        public static string chartYAxisLabel {
            get {
                return ResourceManager.GetString("chartYAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string ConfigForm_txt {
            get {
                return ResourceManager.GetString("ConfigForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string dgvColumnSave {
            get {
                return ResourceManager.GetString("dgvColumnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string dgvColumnVarName {
            get {
                return ResourceManager.GetString("dgvColumnVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo valor.
        /// </summary>
        public static string dgvColumnVarNewValue {
            get {
                return ResourceManager.GetString("dgvColumnVarNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor actual.
        /// </summary>
        public static string dgvColumnVarOldValue {
            get {
                return ResourceManager.GetString("dgvColumnVarOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo no válido.
        /// </summary>
        public static string ErrorFileNoValid {
            get {
                return ResourceManager.GetString("ErrorFileNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto debe tener al menos una variable..
        /// </summary>
        public static string ErrorNoProVars {
            get {
                return ResourceManager.GetString("ErrorNoProVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un Nombre de Proyecto válido.
        /// </summary>
        public static string ErrorNoProyectName {
            get {
                return ResourceManager.GetString("ErrorNoProyectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un Tipo de Conexión de Variable válida.
        /// </summary>
        public static string ErrorNoVarConnectionType {
            get {
                return ResourceManager.GetString("ErrorNoVarConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un Nombre de Variable válido.
        /// </summary>
        public static string ErrorNoVarName {
            get {
                return ResourceManager.GetString("ErrorNoVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un Tipo de Variable válido.
        /// </summary>
        public static string ErrorNoVarType {
            get {
                return ResourceManager.GetString("ErrorNoVarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la conexión.
        /// </summary>
        public static string ErrorSerialPortConnectionKey {
            get {
                return ResourceManager.GetString("ErrorSerialPortConnectionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un Nombre de Variable distinto a las anteriores..
        /// </summary>
        public static string ErrorVarRepeated {
            get {
                return ResourceManager.GetString("ErrorVarRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva variable.
        /// </summary>
        public static string gbNewVar_txt {
            get {
                return ResourceManager.GetString("gbNewVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles.
        /// </summary>
        public static string gBoxControls_txt {
            get {
                return ResourceManager.GetString("gBoxControls_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string gBoxProyect_txt {
            get {
                return ResourceManager.GetString("gBoxProyect_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del proyecto.
        /// </summary>
        public static string gbProyectDetails_txt {
            get {
                return ResourceManager.GetString("gbProyectDetails_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione las variables con las que quiere trabajar.
        /// </summary>
        public static string gbVarSelection_txt {
            get {
                return ResourceManager.GetString("gbVarSelection_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de valores mostrados.
        /// </summary>
        public static string lblChartAmount_txt {
            get {
                return ResourceManager.GetString("lblChartAmount_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string lblConfigProDesc_txt {
            get {
                return ResourceManager.GetString("lblConfigProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del proyecto.
        /// </summary>
        public static string lblConfigProName_txt {
            get {
                return ResourceManager.GetString("lblConfigProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del proyecto.
        /// </summary>
        public static string lblConfigTitle_txt {
            get {
                return ResourceManager.GetString("lblConfigTitle_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puertos.
        /// </summary>
        public static string lblPorts_txt {
            get {
                return ResourceManager.GetString("lblPorts_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string lblProDesc_txt {
            get {
                return ResourceManager.GetString("lblProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto:.
        /// </summary>
        public static string lblProName_txt {
            get {
                return ResourceManager.GetString("lblProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir.
        /// </summary>
        public static string lblReceive_txt {
            get {
                return ResourceManager.GetString("lblReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables modificables.
        /// </summary>
        public static string lblRWVariables_txt {
            get {
                return ResourceManager.GetString("lblRWVariables_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione variable.
        /// </summary>
        public static string lblSelectVar_txt {
            get {
                return ResourceManager.GetString("lblSelectVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string lblSend_txt {
            get {
                return ResourceManager.GetString("lblSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de acceso.
        /// </summary>
        public static string lblVarAccess_txt {
            get {
                return ResourceManager.GetString("lblVarAccess_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de la placa.
        /// </summary>
        public static string lblVarBoardUnits_txt {
            get {
                return ResourceManager.GetString("lblVarBoardUnits_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de comunicación.
        /// </summary>
        public static string lblVarCommunicationType_txt {
            get {
                return ResourceManager.GetString("lblVarCommunicationType_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string lblVarDesc_txt {
            get {
                return ResourceManager.GetString("lblVarDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades en la interfaz.
        /// </summary>
        public static string lblVarInterfaceUnits_txt {
            get {
                return ResourceManager.GetString("lblVarInterfaceUnits_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuste lineal (a*origen + b).
        /// </summary>
        public static string lblVarLinearAdjust_txt {
            get {
                return ResourceManager.GetString("lblVarLinearAdjust_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblVarName_txt {
            get {
                return ResourceManager.GetString("lblVarName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango (min - max).
        /// </summary>
        public static string lblVarRange_txt {
            get {
                return ResourceManager.GetString("lblVarRange_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string lblVarType_txt {
            get {
                return ResourceManager.GetString("lblVarType_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen vectorial.
        /// </summary>
        public static string lblVectFile_txt {
            get {
                return ResourceManager.GetString("lblVectFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaz Planta Piloto.
        /// </summary>
        public static string MainForm_txt {
            get {
                return ResourceManager.GetString("MainForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de configuración |*.txt.
        /// </summary>
        public static string showDialogFilter {
            get {
                return ResourceManager.GetString("showDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione archivo de configuración.
        /// </summary>
        public static string showDialogTitle {
            get {
                return ResourceManager.GetString("showDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes (*.BMP;*.JPG;*.GIF)|*.BMP;*.JPG;*.GIF.
        /// </summary>
        public static string showLoadImageDialogFilter {
            get {
                return ResourceManager.GetString("showLoadImageDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una imagen para cargar.
        /// </summary>
        public static string showLoadImageDialogTitle {
            get {
                return ResourceManager.GetString("showLoadImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string toolStripMenuItemAbout_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemAbout_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicaciones.
        /// </summary>
        public static string toolStripMenuItemCommunication_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCommunication_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string toolStripMenuItemConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear configuración.
        /// </summary>
        public static string toolStripMenuItemCreateConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCreateConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string toolStripMenuItemEnglish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemEnglish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelpHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelpHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string toolStripMenuItemLanguage_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLanguage_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar configuración.
        /// </summary>
        public static string toolStripMenuItemLoadConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLoadConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar configuración.
        /// </summary>
        public static string toolStripMenuItemModifyConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemModifyConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string toolStripMenuItemOthers_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemOthers_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string toolStripMenuItemSerie_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSerie_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string toolStripMenuItemSpanish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSpanish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual de usuario.
        /// </summary>
        public static string toolStripMenuItemUserManual_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemUserManual_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de Variables.
        /// </summary>
        public static string VarSelectionForm_txt {
            get {
                return ResourceManager.GetString("VarSelectionForm_txt", resourceCulture);
            }
        }
    }
}
