//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantaPiloto.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlantaPiloto.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string AboutForm_txt {
            get {
                return ResourceManager.GetString("AboutForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear gráficas.
        /// </summary>
        public static string btnAcceptChart_txt {
            get {
                return ResourceManager.GetString("btnAcceptChart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear archivo.
        /// </summary>
        public static string btnAcceptFile_txt {
            get {
                return ResourceManager.GetString("btnAcceptFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar valores.
        /// </summary>
        public static string btnAcceptVars_txt {
            get {
                return ResourceManager.GetString("btnAcceptVars_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir variable.
        /// </summary>
        public static string btnAddVar_txt {
            get {
                return ResourceManager.GetString("btnAddVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios en la variable.
        /// </summary>
        public static string btnAddVarModify_txt {
            get {
                return ResourceManager.GetString("btnAddVarModify_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancel_txt {
            get {
                return ResourceManager.GetString("btnCancel_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficas.
        /// </summary>
        public static string btnChart_txt {
            get {
                return ResourceManager.GetString("btnChart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        public static string btnChartAmount_txt {
            get {
                return ResourceManager.GetString("btnChartAmount_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string btnClose_txt {
            get {
                return ResourceManager.GetString("btnClose_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnExit_txt {
            get {
                return ResourceManager.GetString("btnExit_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string btnFile_txt {
            get {
                return ResourceManager.GetString("btnFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener guardado.
        /// </summary>
        public static string btnFileStop_txt {
            get {
                return ResourceManager.GetString("btnFileStop_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string btnFinish_txt {
            get {
                return ResourceManager.GetString("btnFinish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lanzar aplicación.
        /// </summary>
        public static string btnLaunchWebApp_txt {
            get {
                return ResourceManager.GetString("btnLaunchWebApp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar imagen.
        /// </summary>
        public static string btnLoadImage_txt {
            get {
                return ResourceManager.GetString("btnLoadImage_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        public static string btnOpen_txt {
            get {
                return ResourceManager.GetString("btnOpen_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibir.
        /// </summary>
        public static string btnReceive_txt {
            get {
                return ResourceManager.GetString("btnReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string btnRefreshPorts_txt {
            get {
                return ResourceManager.GetString("btnRefreshPorts_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string btnSaveConfig_txt {
            get {
                return ResourceManager.GetString("btnSaveConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string btnSend_txt {
            get {
                return ResourceManager.GetString("btnSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string btnStart_txt {
            get {
                return ResourceManager.GetString("btnStart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variables.
        /// </summary>
        public static string btnVar_txt {
            get {
                return ResourceManager.GetString("btnVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráfica.
        /// </summary>
        public static string ChartForm_txt {
            get {
                return ResourceManager.GetString("ChartForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundos.
        /// </summary>
        public static string chartXAxisLabel {
            get {
                return ResourceManager.GetString("chartXAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores.
        /// </summary>
        public static string chartYAxisLabel {
            get {
                return ResourceManager.GetString("chartYAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string ConfigForm_txt {
            get {
                return ResourceManager.GetString("ConfigForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear configuración.
        /// </summary>
        public static string ConfigFormCreate_txt {
            get {
                return ResourceManager.GetString("ConfigFormCreate_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar configuración.
        /// </summary>
        public static string ConfigFormModify_txt {
            get {
                return ResourceManager.GetString("ConfigFormModify_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string dgvColumnSave {
            get {
                return ResourceManager.GetString("dgvColumnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable.
        /// </summary>
        public static string dgvColumnVarName {
            get {
                return ResourceManager.GetString("dgvColumnVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo valor.
        /// </summary>
        public static string dgvColumnVarNewValue {
            get {
                return ResourceManager.GetString("dgvColumnVarNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor actual.
        /// </summary>
        public static string dgvColumnVarOldValue {
            get {
                return ResourceManager.GetString("dgvColumnVarOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, finalice la comunicación con el puerto serie pulsando en el botón &apos;Fin&apos; y vuelva a iniciarla.
        /// </summary>
        public static string ErrorConnectionMsg {
            get {
                return ResourceManager.GetString("ErrorConnectionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo en la conexión.
        /// </summary>
        public static string ErrorConnectionTitle {
            get {
                return ResourceManager.GetString("ErrorConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo no válido.
        /// </summary>
        public static string ErrorFileNoValid {
            get {
                return ResourceManager.GetString("ErrorFileNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto debe tener al menos una variable..
        /// </summary>
        public static string ErrorNoProVars {
            get {
                return ResourceManager.GetString("ErrorNoProVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un Nombre de Proyecto válido.
        /// </summary>
        public static string ErrorNoProyectName {
            get {
                return ResourceManager.GetString("ErrorNoProyectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un Tipo de Conexión de Variable válida.
        /// </summary>
        public static string ErrorNoVarConnectionType {
            get {
                return ResourceManager.GetString("ErrorNoVarConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un Nombre de Variable válido.
        /// </summary>
        public static string ErrorNoVarName {
            get {
                return ResourceManager.GetString("ErrorNoVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un rango válido para la variable.
        /// </summary>
        public static string ErrorNoVarRange {
            get {
                return ResourceManager.GetString("ErrorNoVarRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un Tipo de Variable válido.
        /// </summary>
        public static string ErrorNoVarType {
            get {
                return ResourceManager.GetString("ErrorNoVarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión.
        /// </summary>
        public static string ErrorSerialPortConnectionKey {
            get {
                return ResourceManager.GetString("ErrorSerialPortConnectionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un Nombre de Variable distinto a las anteriores..
        /// </summary>
        public static string ErrorVarRepeated {
            get {
                return ResourceManager.GetString("ErrorVarRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete la varible.
        /// </summary>
        public static string ErrorVarTitle {
            get {
                return ResourceManager.GetString("ErrorVarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva variable.
        /// </summary>
        public static string gbNewVar_txt {
            get {
                return ResourceManager.GetString("gbNewVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles.
        /// </summary>
        public static string gBoxControls_txt {
            get {
                return ResourceManager.GetString("gBoxControls_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string gBoxProyect_txt {
            get {
                return ResourceManager.GetString("gBoxProyect_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del proyecto.
        /// </summary>
        public static string gbProyectDetails_txt {
            get {
                return ResourceManager.GetString("gbProyectDetails_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione las variables con las que quiere trabajar.
        /// </summary>
        public static string gbVarSelection_txt {
            get {
                return ResourceManager.GetString("gbVarSelection_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variables seleccionadas.
        /// </summary>
        public static string gbVarValues_txt {
            get {
                return ResourceManager.GetString("gbVarValues_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación Web.
        /// </summary>
        public static string gbWebApp_txt {
            get {
                return ResourceManager.GetString("gbWebApp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grado en Ingeniería Informática..
        /// </summary>
        public static string lblAboutDegree_txt {
            get {
                return ResourceManager.GetString("lblAboutDegree_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto de Fin de Grado realizado por Francisco Crespo Diez..
        /// </summary>
        public static string lblAboutDesc_txt {
            get {
                return ResourceManager.GetString("lblAboutDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz para Planta Piloto.
        /// </summary>
        public static string lblAboutTitle_txt {
            get {
                return ResourceManager.GetString("lblAboutTitle_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universidad de Burgos..
        /// </summary>
        public static string lblAboutUni_txt {
            get {
                return ResourceManager.GetString("lblAboutUni_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de valores mostrados.
        /// </summary>
        public static string lblChartAmount_txt {
            get {
                return ResourceManager.GetString("lblChartAmount_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string lblConfigProDesc_txt {
            get {
                return ResourceManager.GetString("lblConfigProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del proyecto.
        /// </summary>
        public static string lblConfigProName_txt {
            get {
                return ResourceManager.GetString("lblConfigProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del proyecto.
        /// </summary>
        public static string lblConfigTitle_txt {
            get {
                return ResourceManager.GetString("lblConfigTitle_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a String de conexión de la base de datos.
        /// </summary>
        public static string lblConnectionString_txt {
            get {
                return ResourceManager.GetString("lblConnectionString_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta IISExpress.
        /// </summary>
        public static string lblIISlocation_txt {
            get {
                return ResourceManager.GetString("lblIISlocation_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección IP.
        /// </summary>
        public static string lblIP_txt {
            get {
                return ResourceManager.GetString("lblIP_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto.
        /// </summary>
        public static string lblPort_txt {
            get {
                return ResourceManager.GetString("lblPort_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puertos.
        /// </summary>
        public static string lblPorts_txt {
            get {
                return ResourceManager.GetString("lblPorts_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        public static string lblProDesc_txt {
            get {
                return ResourceManager.GetString("lblProDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta del archivo de proyecto.
        /// </summary>
        public static string lblProjectPath_txt {
            get {
                return ResourceManager.GetString("lblProjectPath_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto:.
        /// </summary>
        public static string lblProName_txt {
            get {
                return ResourceManager.GetString("lblProName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibir.
        /// </summary>
        public static string lblReceive_txt {
            get {
                return ResourceManager.GetString("lblReceive_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variables modificables.
        /// </summary>
        public static string lblRWVariables_txt {
            get {
                return ResourceManager.GetString("lblRWVariables_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione variable.
        /// </summary>
        public static string lblSelectVar_txt {
            get {
                return ResourceManager.GetString("lblSelectVar_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string lblSend_txt {
            get {
                return ResourceManager.GetString("lblSend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de acceso.
        /// </summary>
        public static string lblVarAccess_txt {
            get {
                return ResourceManager.GetString("lblVarAccess_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de la placa.
        /// </summary>
        public static string lblVarBoardUnits_txt {
            get {
                return ResourceManager.GetString("lblVarBoardUnits_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de comunicación.
        /// </summary>
        public static string lblVarCommunicationType_txt {
            get {
                return ResourceManager.GetString("lblVarCommunicationType_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string lblVarDesc_txt {
            get {
                return ResourceManager.GetString("lblVarDesc_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades en la interfaz.
        /// </summary>
        public static string lblVarInterfaceUnits_txt {
            get {
                return ResourceManager.GetString("lblVarInterfaceUnits_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajuste lineal (a*origen + b).
        /// </summary>
        public static string lblVarLinearAdjust_txt {
            get {
                return ResourceManager.GetString("lblVarLinearAdjust_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lblVarName_txt {
            get {
                return ResourceManager.GetString("lblVarName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango (min - max).
        /// </summary>
        public static string lblVarRange_txt {
            get {
                return ResourceManager.GetString("lblVarRange_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string lblVarType_txt {
            get {
                return ResourceManager.GetString("lblVarType_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen vectorial.
        /// </summary>
        public static string lblVectFile_txt {
            get {
                return ResourceManager.GetString("lblVectFile_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta Aplicación Web.
        /// </summary>
        public static string lblWebAppPath_txt {
            get {
                return ResourceManager.GetString("lblWebAppPath_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lab Plant Interface.
        /// </summary>
        public static string MainForm_txt {
            get {
                return ResourceManager.GetString("MainForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de configuración |*.txt.
        /// </summary>
        public static string showDialogFilter {
            get {
                return ResourceManager.GetString("showDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione archivo de configuración.
        /// </summary>
        public static string showDialogTitle {
            get {
                return ResourceManager.GetString("showDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imágenes (*.BMP;*.JPG;*.GIF)|*.BMP;*.JPG;*.GIF.
        /// </summary>
        public static string showLoadImageDialogFilter {
            get {
                return ResourceManager.GetString("showLoadImageDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una imagen para cargar.
        /// </summary>
        public static string showLoadImageDialogTitle {
            get {
                return ResourceManager.GetString("showLoadImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string toolStripMenuItemAbout_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemAbout_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicaciones.
        /// </summary>
        public static string toolStripMenuItemCommunication_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCommunication_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string toolStripMenuItemConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear configuración.
        /// </summary>
        public static string toolStripMenuItemCreateConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemCreateConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string toolStripMenuItemEnglish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemEnglish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string toolStripMenuItemHelpHelp_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelpHelp_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string toolStripMenuItemLanguage_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLanguage_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar configuración.
        /// </summary>
        public static string toolStripMenuItemLoadConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemLoadConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar configuración.
        /// </summary>
        public static string toolStripMenuItemModifyConfig_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemModifyConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros.
        /// </summary>
        public static string toolStripMenuItemOthers_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemOthers_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string toolStripMenuItemSerie_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSerie_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string toolStripMenuItemSpanish_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemSpanish_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual de usuario.
        /// </summary>
        public static string toolStripMenuItemUserManual_txt {
            get {
                return ResourceManager.GetString("toolStripMenuItemUserManual_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de Variables.
        /// </summary>
        public static string VarSelectionForm_txt {
            get {
                return ResourceManager.GetString("VarSelectionForm_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores de variables.
        /// </summary>
        public static string VarValuesForm_txt {
            get {
                return ResourceManager.GetString("VarValuesForm_txt", resourceCulture);
            }
        }
    }
}
